services:
  logbo-bot:
    image: ghcr.io/haibalaryo/logbo-bot:latest
    container_name: logbo-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"  # ホストの3001番をコンテナの3000番に繋ぐ